application: hedukor-1176
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /static
  static_dir: static

- url: /static/images
  static_dir: static/img
 
- url: /static/fonts
  static_dir: static/fonts
  
- url: /static/css
  static_dir: static/css

- url: /static/api
  static_dir: static/api

- url: /static/js
  static_dir: static/js
    
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  
- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
  
builtins:
- remote_api: on